### ISSUE TITLE
Future request: Option to print out NAMES

### ISSUE THREAD

**Issue by AiAe** [numberoverzero/bottom#34]
Option to get all users in channel with NAMES.
https://en.wikipedia.org/wiki/List_of_Internet_Relay_Chat_commands#NAMES

**Comment by numberoverzero** [comment]
Seems reasonable; do you want to give it a shot?  Otherwise I'll try to take a look before the holiday's over.

**Comment by numberoverzero** [comment]
Actually, I think NAMES is supported.

* Packing: [`NAMES`](https://github.com/numberoverzero/bottom/blob/765dca6b180cc2c9fc3048fd04ca3c99b11f7a60/bottom/pack.py#L204)
* Unpacking: [`RPL_NAMREPLY`](https://github.com/numberoverzero/bottom/blob/765dca6b180cc2c9fc3048fd04ca3c99b11f7a60/bottom/unpack.py#L226) and [`RPL_ENDOFNAMES`](https://github.com/numberoverzero/bottom/blob/765dca6b180cc2c9fc3048fd04ca3c99b11f7a60/bottom/unpack.py#L272)

Is there something missing or a parsing error?

**Comment by numberoverzero** [comment]
Closing since bottom is handling `NAMES` correctly.  Feel free to re-open if I've misunderstood.
